---
- name: create Loppback999 on routers
  hosts: automation
  connection: network_cli
  gather_facts: no

  tasks:
# Create the Loopback999 without an IP address. By default, the Interface loopback is always in 'up/up' state right after we create it.
   - name: Create interface Loopback999 without an IP_Address
     ios_interface:
      name: Loopback999
      description: Routing RID - VRF MPLS 

# Save the configuration
   - name: save running to startup when modified
     ios_config:
      save_when: modified


