####################################
## Author: 	Hung Tran  
## Python: 	Python 3.6.8  
## Ansible:	ansible 2.8.5  
## Cisco IOS:	Version 15.5(2)T  
## Built date:	27.09.2019  
## Tested date: 27.09.2019  
####################################

---
- name: configure cisco routers
  hosts: automation
  connection: network_cli
  gather_facts: no
  vars:
    dns: "8.8.8.8 8.8.4.4"

# We make changes with the following task without saving the configuration
# Ansible returns with "changed" results

  tasks:
   - name: configure DNS
     ios_config:
       lines: ip name-server {{dns}}
