####################################
## Author: 	Hung Tran  
## Python: 	Python 3.6.8  
## Ansible:	ansible 2.8.5  
## Cisco IOS:	Version 15.5(2)T  
## Built date:	27.09.2019  
## Tested date: 27.09.2019  
####################################

---
- name: show configuration on Cisco devices
  hosts: automation
  connection: network_cli
  gather_facts: no
  vars:
    dns: "8.8.8.8 8.8.4.4"

  tasks:
   - name: Display name-server configuration
     ios_command:
       commands: show run | i name-server
     register: name_server_output

**"msg='{{name_server_output.stdout_lines}}'"**
#
  - debug: 
     "msg='{{name_server_output.stdout_lines}}'"
#

**"msg='{{name_server_output.stdout_lines}}'"**
#
  - debug: "msg='{{name_server_output.stdout_lines}}'"
#
#####
**msg: "{{name_server_output.stdout_lines}}"**
#
  - debug:
      msg: "{{name_server_output.stdout_lines}}"
 #

**"{{name_server_output.stdout}}"t**
#
  - debug:
      msg: "{{name_server_output.stdout}}"

**var: name_server_output.stdout**
#
  - debug:
      var: name_server_output.stdout
#
[root@netlabbuilder ansible]# ansible-playbook -k playbooks/show_name_server.yml
SSH password: 

PLAY [show configuration on Cisco devices] **********************************************************************************************************

TASK [Display name-server configuration] ************************************************************************************************************
ok: [automation_01]
ok: [automation_02]

TASK [debug] ****************************************************************************************************************************************
ok: [automation_02] => {
    "name_server_output.stdout": [
        "ip name-server 8.8.8.8\nip name-server 8.8.4.4"
    ]
}
ok: [automation_01] => {
    "name_server_output.stdout": [
        "ip name-server 8.8.8.8\nip name-server 8.8.4.4"
    ]
}

PLAY RECAP ******************************************************************************************************************************************
automation_01              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
automation_02              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


##### **var: name_server_output.stdout_lines**
#
  - debug:
      var: name_server_output.stdout_lines
#
[root@netlabbuilder ansible]# ansible-playbook -k playbooks/show_name_server.yml
SSH password: 

PLAY [show configuration on Cisco devices] **********************************************************************************************************

TASK [Display name-server configuration] ************************************************************************************************************
ok: [automation_01]
ok: [automation_02]

TASK [debug] ****************************************************************************************************************************************
ok: [automation_01] => {
    "name_server_output.stdout_lines": [
        [
            "ip name-server 8.8.8.8",
            "ip name-server 8.8.4.4"
        ]
    ]
}
ok: [automation_02] => {
    "name_server_output.stdout_lines": [
        [
            "ip name-server 8.8.8.8",
            "ip name-server 8.8.4.4"
        ]
    ]
}

PLAY RECAP ******************************************************************************************************************************************
automation_01              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
automation_02              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

#####
