####################################
## Author: 	Hung Tran  
## Python: 	Python 3.6.8  
## Ansible:	ansible 2.8.5  
## Cisco IOS:	Version 15.5(2)T  
## Built date:	29.09.2019  
## Tested date: 29.09.2019  
####################################

---
- name: create Loppback999 on routers
  hosts: automation
  connection: network_cli
  gather_facts: no

  tasks:
# Create the Loopback999 without an IP address. By default, the Interface loopback is always in 'up/up' state right after we create it.
   - name: Create interface Loopback999 without an IP_Address
     ios_interface:
      name: Loopback999
      description: Routing RID - VRF MPLS 

# Save the configuration
   - name: save running to startup when modified
     ios_config:
      save_when: modified


